"""recreate schema as uuid

Revision ID: 01783139d85c
Revises: 
Create Date: 2026-03-19 23:54:47.317316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01783139d85c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('currency', sa.String(length=6), nullable=True),
    sa.Column('full_name', sa.String(length=60), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('sender_id', sa.Uuid(), nullable=True),
    sa.Column('receiver_email', sa.String(length=40), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_type', sa.String(length=15), nullable=True),
    sa.Column('currency', sa.String(length=6), nullable=True),
    sa.Column('initial_balance', sa.Float(), nullable=True),
    sa.Column('remaining_balance', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_email'], ['users.email'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index('ix_users_email_lower', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
