"""feat: (transactions use email to identify receiver to enhance security)

Revision ID: f8b55a543ccf
Revises: a1ab877cfaf2
Create Date: 2026-03-18 20:43:58.302566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8b55a543ccf'
down_revision: Union[str, Sequence[str], None] = 'a1ab877cfaf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('receiver_email', sa.String(length=40), nullable=True))
    op.drop_constraint(op.f('transactions_receiver_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['receiver_email'], ['email'])
    op.drop_column('transactions', 'receiver_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_receiver_id_fkey'), 'transactions', 'users', ['receiver_id'], ['user_id'])
    op.drop_column('transactions', 'receiver_email')
    # ### end Alembic commands ###
